agent:
  url: "http://localhost:8080"
  interval: 5s
  source: "my-device-agent"
  metrics:
    cpu_usage: true
    memory_usage: false
    disk_usage: true
    network_io_in: true
    network_io_out: true
    uptime: true

  verbose: true


aggregator:
  port: "8080"
  max_age: 1h
  verbose: true