name: CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  build:
    # Run on an Ubuntu runner (latest version as of March 2025)
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment with the version from go.mod (1.21)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      # Install dependencies
      - name: Get dependencies
        run: go mod tidy

      # Build the agent and aggregator binaries
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o pulselite-agent-linux-amd64 cmd/agent/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-agent-linux-arm64 cmd/agent/main.go
          GOOS=linux GOARCH=amd64 go build -o pulselite-aggregator-linux-amd64 cmd/aggregator/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-aggregator-linux-arm64 cmd/aggregator/main.go

      # Placeholder for tests (uncomment when tests are added)
      # - name: Run Tests
      #   run: go test ./...

      # Upload the built binaries as artifacts
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: pulselite-binaries
          path: |
            pulselite-agent-linux-amd64
            pulselite-agent-linux-arm64
            pulselite-aggregator-linux-amd64
            pulselite-aggregator-linux-arm64