name: CI

# Trigger the workflow on push or pull request to the main branch, and on tags for releases
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # Trigger on tags like v1.0.0
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  build:
    # Run on an Ubuntu runner (latest version as of March 2025)
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment with the version from go.mod (1.24.1)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      # Install dependencies
      - name: Get dependencies
        run: go mod tidy

      # Build the agent and aggregator binaries for multiple architectures
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o pulselite-agent-linux-amd64 cmd/agent/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-agent-linux-arm64 cmd/agent/main.go
          GOOS=linux GOARCH=amd64 go build -o pulselite-aggregator-linux-amd64 cmd/aggregator/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-aggregator-linux-arm64 cmd/aggregator/main.go

  
      # Upload the built binaries as workflow artifacts
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: pulselite-binaries
          path: |
            pulselite-agent-linux-amd64
            pulselite-agent-linux-arm64
            pulselite-aggregator-linux-amd64
            pulselite-aggregator-linux-arm64

      # Zip binaries for release (only on tag push)
      - name: Zip Binaries
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: zip pulselite-binaries.zip pulselite-agent-linux-* pulselite-aggregator-linux-*

      # Create a GitHub Release (only on tag push)
      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload zipped binaries as release assets (only on tag push)
      - name: Upload Release Assets
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} # Reference to Create Release step
          asset_path: ./pulselite-binaries.zip
          asset_name: pulselite-binaries-${{ github.ref_name }}.zip
          asset_content_type: application/zip