name: PR Build

# Trigger the workflow on push or pull request to the main branch, and on tags for releases
on:
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Get dependencies
        run: go mod tidy
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o pulselite-agent-linux-amd64 cmd/agent/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-agent-linux-arm64 cmd/agent/main.go
          GOOS=linux GOARCH=amd64 go build -o pulselite-aggregator-linux-amd64 cmd/aggregator/main.go
          GOOS=linux GOARCH=arm64 go build -o pulselite-aggregator-linux-arm64 cmd/aggregator/main.go  
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: pulselite-binaries
          path: |
            pulselite-agent-linux-amd64
            pulselite-agent-linux-arm64
            pulselite-aggregator-linux-amd64
            pulselite-aggregator-linux-arm64

    