name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows ]
        arch: [ amd64 ]
        include:
          - os: linux
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Get dependencies
        run: go mod tidy
      - name: Build Binaries
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o pulselite-agent-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} cmd/agent/main.go
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o pulselite-aggregator-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} cmd/aggregator/main.go
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: pulselite-binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            pulselite-agent-${{ matrix.os }}-${{ matrix.arch }}*
            pulselite-aggregator-${{ matrix.os }}-${{ matrix.arch }}*